import { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  en: {
    // Nav
    home: 'Home',
    events: 'Events',
    profile: 'Profile',
    // Home
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    showUpToday: 'ShowUpToday?',
    readyToPlay: "Ready to play? We'll find you a group.",
    yesImIn: "Yes, I'm in!",
    notToday: 'Not today',
    whatToPlay: 'What do you want to play?',
    pickASport: "Pick a sport and we'll match you",
    findingMatch: 'Finding your match...',
    cancel: 'Cancel',
    youShowedUp: 'You showed up today!',
    checkEvents: 'Check your events below',
    cancelAvailability: 'Cancel availability',
    availableToday: 'Available today',
    yourEvents: 'Your events',
    seeAll: 'See all',
    loading: 'Loading...',
    noEventsYet: 'No events yet. Show up or create one!',
    createAnEvent: 'Create an event',
    confirmed: 'Confirmed',
    waiting: 'Waiting',
    // Events page
    new: 'New',
    loadingEvents: 'Loading events...',
    noEventsFirst: 'No events yet. Be the first to create one!',
    searchEvents: 'Search events...',
    allSports: 'All sports',
    // Profile
    editProfile: 'Edit profile',
    save: 'Save',
    saving: 'Saving...',
    about: 'About',
    mySports: 'My sports',
    noBioYet: 'No bio yet. Tap edit to add one!',
    noSportsYet: 'No sports selected yet. Complete onboarding to add sports!',
    logOut: 'Log out',
    profileUpdated: 'Profile updated!',
    failedSave: 'Failed to save profile',
    photoUploaded: 'Photo uploaded!',
    failedUpload: 'Failed to upload photo',
    analyzePhoto: 'Let AI detect sports from your photo',
    analyzingPhoto: 'Analyzing your photo...',
    aiDetected: 'AI detected from your photo:',
    badges: 'Badges',
    xpToNext: 'XP to next level',
    eventsJoined: 'events joined',
    level: 'Level',
    yourCity: 'Your city',
    // Create event
    createEvent: 'Create event',
    setupGame: 'Set up a game and invite players',
    sport: 'Sport',
    title: 'Title',
    date: 'Date',
    time: 'Time',
    location: 'Location',
    maxPlayers: 'Max players',
    descriptionOptional: 'Description (optional)',
    publicEvent: 'Public event',
    privateEvent: 'Private event',
    anyoneCanJoin: 'Anyone can find and join',
    inviteOnly: 'Invite only',
    creating: 'Creating...',
    eventCreated: 'Event created!',
    fillRequired: 'Please fill in sport, title, and date',
    back: 'Back',
    suggestedVenues: 'Suggested venues:',
    // Event detail
    loadingEvent: 'Loading event...',
    eventNotFound: 'Event not found',
    goBack: 'Go back',
    share: 'Share',
    copied: 'Copied!',
    addToCalendar: 'Add to calendar',
    compatible: 'compatible',
    joinEvent: 'Join this event',
    leaveEvent: 'Leave event',
    players: 'Players',
    createPoll: 'Create a poll',
    newPoll: 'New poll',
    create: 'Create',
    groupChat: 'Group chat',
    noMessages: 'No messages yet. Start the conversation!',
    typeMessage: 'Type a message...',
    you: 'You',
    captain: 'Captain',
    votes: 'votes',
    vote: 'vote',
    addOption: 'Add option',
    // Auth
    logIn: 'Log in',
    signingIn: 'Signing in...',
    emailAddress: 'Email address',
    password: 'Password',
    dontHaveAccount: "Don't have an account?",
    signUp: 'Sign up',
    // Onboarding
    whatDoYouPlay: 'What do you play?',
    pickSports: "Pick all sports you're interested in",
    continue: 'Continue',
    selected: 'selected',
    yourSkillLevel: 'Your skill level',
    matchSkill: 'Helps us match you with similar players',
    almostDone: 'Almost done!',
    tellAboutYourself: 'Tell people a bit about yourself',
    tapToUpload: 'Tap to upload photo (optional)',
    shortBio: "Short bio — e.g. 'Weekend footballer, love playing 5-a-side after work'",
    cityNeighborhood: 'City / neighborhood',
    analyzeBio: 'Let AI suggest sports from your bio',
    analyzingBio: 'Analyzing your bio...',
    bioAnalyzed: 'Bio analyzed!',
    aiDetectedSports: 'AI detected these sports:',
    addedToSelections: 'Added to your selections on step 1',
    letsGo: "Let's go!",
    step: 'Step',
    of: 'of',
    setupProfile: 'Set up your profile',
    welcomeMessage: 'Profile set up! Welcome to ShowUp2Move!',
    failedToSave: 'Failed to save',
  },
  ro: {
    home: 'Acasă',
    events: 'Evenimente',
    profile: 'Profil',
    goodMorning: 'Bună dimineața',
    goodAfternoon: 'Bună ziua',
    goodEvening: 'Bună seara',
    showUpToday: 'Vii azi?',
    readyToPlay: 'Gata de joc? Îți găsim un grup.',
    yesImIn: 'Da, sunt!',
    notToday: 'Nu azi',
    whatToPlay: 'Ce vrei să joci?',
    pickASport: 'Alege un sport și te potrivim',
    findingMatch: 'Căutăm potrivirea...',
    cancel: 'Anulează',
    youShowedUp: 'Ai venit azi!',
    checkEvents: 'Verifică evenimentele mai jos',
    cancelAvailability: 'Anulează disponibilitatea',
    availableToday: 'Disponibili azi',
    yourEvents: 'Evenimentele tale',
    seeAll: 'Vezi tot',
    loading: 'Se încarcă...',
    noEventsYet: 'Niciun eveniment. Arată-te sau creează unul!',
    createAnEvent: 'Creează un eveniment',
    confirmed: 'Confirmat',
    waiting: 'În așteptare',
    new: 'Nou',
    loadingEvents: 'Se încarcă evenimentele...',
    noEventsFirst: 'Niciun eveniment. Fii primul care creează unul!',
    searchEvents: 'Caută evenimente...',
    allSports: 'Toate sporturile',
    editProfile: 'Editează profilul',
    save: 'Salvează',
    saving: 'Se salvează...',
    about: 'Despre',
    mySports: 'Sporturile mele',
    noBioYet: 'Nicio descriere încă. Apasă editare!',
    noSportsYet: 'Niciun sport selectat. Completează onboarding-ul!',
    logOut: 'Deconectare',
    profileUpdated: 'Profil actualizat!',
    failedSave: 'Salvare eșuată',
    photoUploaded: 'Fotografie încărcată!',
    failedUpload: 'Încărcare eșuată',
    analyzePhoto: 'AI detectează sporturi din fotografie',
    analyzingPhoto: 'Se analizează fotografia...',
    aiDetected: 'AI a detectat din fotografia ta:',
    badges: 'Insigne',
    xpToNext: 'XP până la nivelul următor',
    eventsJoined: 'evenimente',
    level: 'Nivel',
    yourCity: 'Orașul tău',
    createEvent: 'Creează eveniment',
    setupGame: 'Configurează un joc și invită jucători',
    sport: 'Sport',
    title: 'Titlu',
    date: 'Dată',
    time: 'Ora',
    location: 'Locație',
    maxPlayers: 'Jucători maximi',
    descriptionOptional: 'Descriere (opțional)',
    publicEvent: 'Eveniment public',
    privateEvent: 'Eveniment privat',
    anyoneCanJoin: 'Oricine poate găsi și se alătura',
    inviteOnly: 'Doar cu invitație',
    creating: 'Se creează...',
    eventCreated: 'Eveniment creat!',
    fillRequired: 'Completează sportul, titlul și data',
    back: 'Înapoi',
    suggestedVenues: 'Locații sugerate:',
    loadingEvent: 'Se încarcă evenimentul...',
    eventNotFound: 'Eveniment negăsit',
    goBack: 'Înapoi',
    share: 'Partajează',
    copied: 'Copiat!',
    addToCalendar: 'Adaugă în calendar',
    compatible: 'compatibil',
    joinEvent: 'Alătură-te',
    leaveEvent: 'Părăsește evenimentul',
    players: 'Jucători',
    createPoll: 'Creează un sondaj',
    newPoll: 'Sondaj nou',
    create: 'Creează',
    groupChat: 'Chat de grup',
    noMessages: 'Niciun mesaj. Începe conversația!',
    typeMessage: 'Scrie un mesaj...',
    you: 'Tu',
    captain: 'Căpitan',
    votes: 'voturi',
    vote: 'vot',
    addOption: 'Adaugă opțiune',
    logIn: 'Conectare',
    signingIn: 'Se conectează...',
    emailAddress: 'Adresa de email',
    password: 'Parola',
    dontHaveAccount: 'Nu ai cont?',
    signUp: 'Înregistrare',
    whatDoYouPlay: 'Ce joci?',
    pickSports: 'Alege sporturile care te interesează',
    continue: 'Continuă',
    selected: 'selectate',
    yourSkillLevel: 'Nivelul tău',
    matchSkill: 'Ne ajută să te potrivim cu jucători similari',
    almostDone: 'Aproape gata!',
    tellAboutYourself: 'Spune-le oamenilor despre tine',
    tapToUpload: 'Apasă pentru foto (opțional)',
    shortBio: "Bio scurt — ex. 'Fotbalist de weekend, ador 5-a-side'",
    cityNeighborhood: 'Oraș / cartier',
    analyzeBio: 'AI sugerează sporturi din bio',
    analyzingBio: 'Se analizează bio-ul...',
    bioAnalyzed: 'Bio analizat!',
    aiDetectedSports: 'AI a detectat aceste sporturi:',
    addedToSelections: 'Adăugate la selecțiile tale de la pasul 1',
    letsGo: 'Hai!',
    step: 'Pasul',
    of: 'din',
    setupProfile: 'Configurează-ți profilul',
    welcomeMessage: 'Profil configurat! Bun venit la ShowUp2Move!',
    failedToSave: 'Salvare eșuată',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  const changeLang = useCallback((l) => {
    setLang(l);
    localStorage.setItem('lang', l);
  }, []);

  const t = useCallback((key) => translations[lang]?.[key] || translations.en[key] || key, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider');
  return ctx;
}
